### ISSUE TITLE
error: QWidget has been deleted

### ISSUE THREAD

**Issue by omega3** [fonol/anki-search-inside-add-card#25] opened 2019-05-05 16:08 UTC
I get the following error while editing card. I edit and close edit window and error show up.

It happened twice and doesn't happen when I disable this add-on.

```
Debug info:
Anki 2.1.12 (eef86bf3) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Linux
Flags: frz=True ao=True sv=2

Caught exception:
  File "aqt/progress.py", line 72, in handler
  File "aqt/editcurrent.py", line 72, in _saveAndClose
  File "aqt/editor.py", line 384, in cleanup
  File "aqt/editor.py", line 309, in setNote
<class 'RuntimeError'>: wrapped C/C++ object of type QWidget has been deleted
```

Operating System: Manjaro Linux 
KDE Plasma Version: 5.15.4
KDE Frameworks Version: 5.57.0
Qt Version: 5.12.3
Kernel Version: 5.0.9-2-MANJARO
OS Type: 64-bit

**Comment by fonol** [comment] 2019-05-06 16:35
Thanks for the report. Are you using the newest version of the add-on?
I fixed a related bug some days ago. If yes, in which edit dialog does this error appear, the one you can open during review or the one you can open from the add card dialog?

**Comment by omega3** [comment] 2019-05-06 18:06
> Are you using the newest version of the add-on?
Yes. I update regularly. 

> in which edit dialog does this error appear
In edit mode - the one you can open during review.

Here are add-ons that I use. I can't think of any that could interact with your add-on. 
Do you have any suggestions?

Do you use the latest Anki or from Ubuntu repository?

**Comment by fonol** [comment] 2019-05-06 18:25
I use the latest one. Your post seems to be missing the addon list. If it is not too much work, you could disable all other add-ons, and try to reproduce the error. Have you set 'useInEdit' to true or false?

**Comment by omega3** [comment] 2019-05-07 08:08
Sorry
https://imgur.com/cN42lVJ

Yes I set 'useInEdit' to true.

When all others are disabled problem doesn't  occurs.

**Comment by fonol** [comment] 2019-05-07 09:30
Okay, when I got some time, I will try some of these to check if they cause the problem.
Just two more questions: 
Does it occur if you enable the other add-ons again and set useInEdit to false?
Does the error occur everytime or just sometimes?

**Comment by omega3** [comment] 2019-05-07 14:07
Hmm. That's strange but now it is ok. 

Perhaps this "enable the other add-ons again and set useInEdit to false"  and re-enabling it repaired it.

**Comment by fonol** [comment] 2019-05-07 16:35
Well, the error sounded a bit like a more general problem, considering the fact that the stacktrace doesn't include code from the add-on (might still have to do with it/some other add-on).
I will close the issue, but feel free to open it again if the problem persists and you are convinced that it is this add-on that is causing the trouble.

**Closed by fonol** 2019-05-07 16:35 UTC
Labels: bug
