### ISSUE TITLE
Some problems occur with pdf capture-paste operation

### ISSUE THREAD

**Issue by comienzo2093** [fonol/anki-search-inside-add-card#220] opened 2021-02-22 09:54 UTC
Hi, I'm not very good at English, so here's a link to a YouTube video on the issue instead.

https://www.youtube.com/watch?v=VY5NZSyU3ec

This is a problem where images are'replaced' in certain situations when performing a capture-paste operation.

As shown in the video,
When performing the same action after entering text, the image was not replaced with the newly captured image.

This is sometimes a problem. For example, it becomes a problem when the content on page 35 and the content on page 36 are connected, so you need to include two images on the anki card. (Of course, there is a simple solution to add any character and then continue capturing)

I am not sure if this is intended or not. However, if this is an add-on error, I would appreciate your fix.

Thank you.

**Comment by fonol** [comment] 2021-02-22 09:56
Hi, thanks for the report, unfortunately I cannot open the video ('This video is private').

**Comment by fonol** [comment] 2021-02-22 10:27
I think I get the error. The way it was intended, it should always append to, and never replace the content of the field.
A fix will be in the next update.

**Comment by comienzo2093** [comment] 2021-02-22 10:57
> Hi, thanks for the report, unfortunately I cannot open the video ('This video is private').

I just changed the video to 'public', thanks.

**Comment by comienzo2093** [comment] 2021-02-25 09:19
> I think I get the error. The way it was intended, it should always append to, and never replace the content of the field.
> A fix will be in the next update.


Hi, As I just checked, I'm not sure, but this issue seems to be resolved as well. 
Did you fix it in the update a little while ago? I think the capture-paste function works normally.
Thank you!

**Closed** 2021-03-03 03:55 UTC
