### ISSUE TITLE
Saving preferences does not work for me.

### ISSUE THREAD

**Issue by BaekToDaFuture** [fonol/anki-search-inside-add-card#64] opened 2020-03-01 15:38 UTC
Anki 2.20 on Mac.

When I am rapidly adding cards, the search slows down my input, so I uncheck all the options for searching on typing, selection, highlights, and all decks. However when I add a card, the default preferences come back.

**Comment by fonol** [comment] 2020-03-01 16:11
Hi, 
do you mean the preferences get activated again after you added a note, or after you closed and reopened the Add dialog? 
If the latter, I guess that's not a bug, as currently, the search on selection and search on typing options are not persisted on closing/reopening. Grid and Highlight should though. I guess it's about time I include the other two options too.

Edit: I just checked, and you are right, the selected decks are reset after adding a card, so that at least is a bug.

**Comment by BaekToDaFuture** [comment] 2020-03-02 01:48
Hello,

Yes, the check marks for the decks are reset and the add-on performs searches even though the other preferences are unchecked as well.

**Comment by fonol** [comment] 2020-03-02 06:22
There is a new update available, please test if the issue is still there for you.

**Closed** 2020-03-04 16:25 UTC
Labels: bug
