### ISSUE TITLE
Cursor Jumps To The Beginning Of Line in 'Edit Note' Dialog Box

### ISSUE THREAD

**Issue by anuragambasth** [fonol/anki-search-inside-add-card#295] opened 2021-09-21 00:50 UTC
**Describe the bug**
When I try to edit a card using 'EDIT NOTE' while reading a PDF, the cursor jumps around and goes to the beginning of the field/box, every few seconds.

**To Reproduce**
1. Open a PDF File
2. Select some text to trigger a search
3. Click on the 'pencil' icon to edit a card displayed in the search box
4. 'Edit Note' dialog opens.
5. Now, when I try to edit the text inside any of the fields (Text, Back Extra, etc.), the cursor jumps around and goes to the beginning of the line or to the beginning of the field.

Note:
1. This does NOT happen when using the Browser to edit the same note. 
2. This does NOT happen when using the EDIT option while reviewing cards.

**Environment (please complete the following information):**
- OS: Windows 10. Version 21H1. OS build: 19043.1202
- Anki version: ⁨2.1.47 (dc156f34)⁩

**Comment by fonol** [comment] 2021-10-01 06:37
Hi, 
I can replicate, don't know what the issue is at the moment though, but I'll investigate.

**Comment by anuragambasth** [comment] 2021-10-01 16:36
> Hi, I can replicate, don't know what the issue is at the moment though, but I'll investigate.

Thank you!

**Comment by Yandrik** [comment] 2021-11-05 15:29
I've had the same issue since I updated to a new version of Anki (2.1.48, but bug still persists for 2.1.49). 
The cursor jumps to the start of the current input field when - as far as I can tell - the card is saved automatically. I think that this is the case because: 
1. When typing continuously, the cursor doesn't jump to the start of the input field
2. When not typing, after around one second, the cursor jumps to the start of the input field
3. When pasting text either from the clipboard or from shortcuts (e.g. `ctrl+m` `e` for `\[\]`) the cursor jumps to the start of the input field instantly. Pasting images shows the same behaviour here.

Hope this helps with identifying the problem

**Comment by WeB829** [comment] 2022-05-23 20:36
Hey, is there still no solution for the bug? I'd love to be able to edit my notes directly from the search results. Instead I need to go to the browser because it's basically uneditable if it jump to the beginning of the page when you pause for a second.

**Comment by OcileCollection** [comment] 2022-08-15 07:38
Would it be possible to close this issue. It seems to be resolved with the latest updates.

**Closed** 2022-08-15 07:39 UTC
Labels: bug
